---
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # Keep version in sync with tox.ini/docs and ci.yml/docs.
    python: "3.13"
  jobs:
    # Need the tags to calculate the version.
    post_checkout:
      - git fetch --tags

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

submodules:
  include: all

sphinx:
  configuration: docs/conf.py
