[tox]
requires =
    tox>=4.51.0
    tox-uv-bare
env_list =
    lint-{ruff,pre-commit},
    3.1{0-5}-{tests,mypy},
    3.14t-tests,
    pypy3.11-tests,
    tests-{bindings-main,system-argon2},
    typing-{pyright,ty,pyrefly,mypy}
    docs-doctests,
    coverage-{combine,report}


[testenv]
description = Run tests / check types and do NOT measure coverage.
runner = uv-venv-lock-runner
package = wheel
wheel_build_env = .pkg
dependency_groups =
    tests: tests
    mypy: typing
pass_env =
    FORCE_COLOR
    NO_COLOR
commands =
    tests: pytest {posargs}
    tests: python -Im argon2 -n 1 -t 1 -m 8 -p 1
    mypy: mypy typing_tests


[testenv:3.1{0,4}-tests]
# Keep coverage-combine's depends with the versions.
description = Run tests and measure coverage.
dependency_groups = cov
commands =
    coverage run -m pytest {posargs}
    coverage run -m argon2 -n 1 -t 1 -m 8 -p 1
    coverage run -m argon2 --profile CHEAPEST


# Split combine/report in 2 to avoid excessive "Combined data file ..." output.
[testenv:coverage-combine]
base_python_file = .python-version-default
# Keep in-sync with test env definition above.
depends = 3.1{0,4}-tests
package = skip
dependency_groups = cov
commands = coverage combine

[testenv:coverage-report]
description = Report coverage over oldest and latest supported Python
base_python_file = .python-version-default
depends = coverage-combine
package = skip
dependency_groups = cov
parallel_show_output = true
commands = coverage report

[testenv:tests-system-argon2]
description = Run tests against bindings that use a system installation of Argon2.
base_python_file = .python-version-default
runner = virtualenv
set_env = ARGON2_CFFI_USE_SYSTEM=1
install_command = pip install {opts} --no-binary=argon2-cffi-bindings {packages}

[testenv:tests-bindings-main]
description = Run tests against the current main branch of argon2-cffi-bindings
base_python_file = .python-version-default
runner = virtualenv
dependency_groups =
deps =
commands_pre = pip install --ignore-installed hypothesis pytest git+https://github.com/hynek/argon2-cffi-bindings
install_command = pip install {opts} --no-deps {packages}


[testenv:lint-{ruff,pre-commit}]
description = Lint the code base.
base_python_file = .python-version-default
package = skip
dependency_groups = lint
commands =
    ruff: ruff check --fix --exit-non-zero-on-fix .
    ruff: ruff format --exit-non-zero-on-format .
    pre-commit: prek run --all-files


[testenv:typing-mypy]
description = Check own code with Mypy.
base_python_file = .python-version-default
dependency_groups = typing
commands = mypy src typing_tests

[testenv:typing-pyright]
description = Check API and own code with Pyright
dependency_groups = pyright
commands = pyright

[testenv:typing-ty]
description = Check API with ty
dependency_groups = ty
commands = ty check

[testenv:typing-pyrefly]
description = Check API with pyrefly
dependency_groups = pyrefly
commands = pyrefly check


[testenv:docs-{build,doctests,linkcheck}]
base_python = 3.14
dependency_groups = docs
commands =
    build: sphinx-build -n -T -W -b html -d {envtmpdir}/doctrees docs {posargs:docs/_build/}html
    doctests: python -m doctest README.md
    doctests: sphinx-build -n -T -W -b doctest -d {envtmpdir}/doctrees docs {posargs:docs/_build/}html
    linkcheck: sphinx-build -W -b linkcheck -d {envtmpdir}/doctrees docs docs/_build/html

[testenv:docs-watch]
package = editable
base_python = {[testenv:docs-build]base_python}
dependency_groups = docs-watch
commands =
    watchfiles \
        --ignore-paths docs/_build/ \
        'sphinx-build -W -n --jobs auto -b html -d {envtmpdir}/doctrees docs docs/_build/html' \
        src \
        docs \
        README.md \
        CHANGELOG.md
